name: Github Actions Workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
<<<<<<< HEAD
    - name: Set up Python 3.12.3
=======
    - name: Set up Python 3.9.19
>>>>>>> 00436fb319d3d08c43610bb37003fbe41a196758
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.3
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Format code
      run: |
        make format
    
